// D-004b: static host config generated by scripts/assemble.ts (vercel.json, 404, robots, sitemap,
// painting.json) and the security headers. scripts/serve.ts uses the same rules for local parity.
import { describe, expect, test } from 'bun:test'
import { createHash } from 'node:crypto'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { validateConfig, getTemplate } from '../packages/core/src/index.ts'
import { CSS } from '../packages/widget/src/styles.ts'
import { devSnippet } from '../apps/web/src/lib/share.ts'
import {
  EMBED_FILES, SITEMAP_PATHS, SITE_URL, SPA_PATHS, headersFor, paintingConfig, robotsTxt, sitemapXml, vercelConfig, widgetStyleHash,
} from './site.ts'

const ROOT = join(import.meta.dir, '..')

describe('SPA routes', () => {
  test('SPA_PATHS are exactly the router paths in apps/web/src/main.tsx', () => {
    const main = readFileSync(join(ROOT, 'apps/web/src/main.tsx'), 'utf8')
    const paths = [...main.matchAll(/path: '([^']+)'/g)].map((m) => m[1]).sort()
    expect([...SPA_PATHS].sort()).toEqual(paths)
  })
  test('vercel.json rewrites only the SPA routes to index.html (no catch-all)', () => {
    const v = vercelConfig()
    expect(v.rewrites.map((r) => r.source).sort()).toEqual(SPA_PATHS.filter((p) => p !== '/').sort())
    for (const r of v.rewrites) {
      expect(r.destination).toBe('/index.html')
      expect(r.source).not.toMatch(/[(*]/)
    }
  })
})

describe('robots and sitemap', () => {
  test('robots.txt allows all and points at the sitemap', () => {
    expect(robotsTxt()).toBe(`User-agent: *\nAllow: /\n\nSitemap: ${SITE_URL}/sitemap.xml\n`)
  })
  test('sitemap.xml lists the public pages on the production origin', () => {
    const xml = sitemapXml()
    expect(xml.startsWith('<?xml version="1.0" encoding="UTF-8"?>')).toBe(true)
    const locs = [...xml.matchAll(/<loc>([^<]+)<\/loc>/g)].map((m) => m[1])
    expect(locs).toEqual(SITEMAP_PATHS.map((p) => SITE_URL + p))
    expect(SITEMAP_PATHS).toContain('/')
    expect(SITEMAP_PATHS).not.toContain('/q') // a share page without a config is empty
  })
})

describe('developer snippet', () => {
  test('painting.json is a valid config: the painting-en template', () => {
    const r = validateConfig(paintingConfig())
    expect(r.ok).toBe(true)
    expect(paintingConfig()).toEqual(getTemplate('painting-en'))
  })
  test('every URL in the landing snippet is a file assemble ships', () => {
    const urls = [...devSnippet('https://quotelet.example').matchAll(/(?:src|data-config-url)="([^"]+)"/g)].map((m) => m[1])
    expect(urls.length).toBe(2)
    for (const u of urls) {
      expect(u.startsWith('https://quotelet.example/')).toBe(true)
      expect(EMBED_FILES).toContain(new URL(u).pathname)
    }
  })
})

describe('security headers', () => {
  const app = ['/', '/build', '/q', '/aperto', '/it/quanto-costa-imbiancare', '/index.html', '/nope', '/robots.txt']
  const embed = ['/quotelet.js', '/painting.json', '/fixtures/config-imbianchino.json', '/harness/index.html', '/api/aperto', '/assets/index-x.js']
  test('every path gets nosniff and strict-origin-when-cross-origin', () => {
    for (const p of [...app, ...embed]) {
      expect(headersFor(p)['X-Content-Type-Options'], p).toBe('nosniff')
      expect(headersFor(p)['Referrer-Policy'], p).toBe('strict-origin-when-cross-origin')
    }
  })
  test('app pages get a strict CSP with frame-ancestors none', () => {
    const csp = headersFor('/')['Content-Security-Policy']
    for (const d of ["default-src 'self'", "script-src 'self'", "connect-src 'self' https://formsubmit.co", "form-action 'self' https://formsubmit.co",
      "img-src 'self' data:", "font-src 'self' data:", "object-src 'none'", "base-uri 'self'", "frame-ancestors 'none'"]) expect(csp).toContain(d)
    expect(csp).toContain(`style-src 'self' '${widgetStyleHash()}'`)
    expect(csp).not.toContain('unsafe-inline')
    expect(csp).not.toContain('unsafe-eval')
    for (const p of app) expect(headersFor(p)['Content-Security-Policy'], p).toBe(csp)
  })
  test('embed and static paths get no CSP / frame-ancestors; JSON configs allow any origin', () => {
    for (const p of embed) expect(headersFor(p)['Content-Security-Policy'], p).toBeUndefined()
    expect(headersFor('/painting.json')['Access-Control-Allow-Origin']).toBe('*')
    expect(headersFor('/fixtures/config-imbianchino.json')['Access-Control-Allow-Origin']).toBe('*')
    expect(headersFor('/')['Access-Control-Allow-Origin']).toBeUndefined()
  })
  test("the widget's shadow <style> is allowed by hash", () => {
    expect(widgetStyleHash()).toBe(`sha256-${createHash('sha256').update(CSS).digest('base64')}`)
  })
  test('vercel.json headers carry the same rules', () => {
    const v = vercelConfig()
    expect(v.headers.length).toBeGreaterThanOrEqual(3)
    const all = v.headers.find((h) => h.source === '/(.*)')!
    expect(all.headers).toContainEqual({ key: 'X-Content-Type-Options', value: 'nosniff' })
    const cspRule = v.headers.find((h) => h.headers.some((x) => x.key === 'Content-Security-Policy'))!
    expect(cspRule.source).toContain('quotelet\\.js')
    expect(cspRule.source).toContain('painting\\.json')
  })
})
